toggle_hotkey = "SUPER+SPACE"
clipboard_hotkey = "SUPER+SHIFT+C"
placeholder = "Time to be productive!"
search_url = "https://duckduckgo.com/search?q=%s"
haptic_feedback = false
show_trayicon = true
search_dirs = ["~"]
auto_suggest = false
log_path = "/tmp/rustcast.log"
debounce_delay = 300

[buffer_rules]
clear_on_hide = true
clear_on_enter = true

[theme]
text_color = [
    1.0,
    1.0,
    1.0,
]
background_color = [
    0.0,
    0.0,
    0.0,
]
blur = false
show_icons = true
show_scroll_bar = false

[[shells]]
command = "~/.config/rustcast/sites.sh n8n"
alias = "Open n8n"
alias_lc = "n8n"

[[shells]]
command = "~/.config/rustcast/sites.sh search"
alias = "Open Searxng"
alias_lc = "search"

[[shells]]
command = "~/.config/rustcast/sites.sh ai"
alias = "Open OWUI"
alias_lc = "owui"

[modes]
presentation = "~/.config/rustcast/sites.sh ms"
default = ""

[aliases]
ff = "firefox"
open = "owui"
